export const branddata = [
  {
    brand: "Toyota",
    activation: true,
    models: [
      {
        activation: true,
        model: "Vios",
        type: "Sedan",
        versions: [
          {
            activation: true,
            version: "E CVT",
            fuel: "Petrol",
            years: [
              {
                activation: true,
                year: "2021",
                transmission: "Automatic",
                tier: 2,
                originalprice: 520000000,
              },
              {
                activation: true,
                year: "2022",
                transmission: "Automatic",
                tier: 2,
                originalprice: 540000000,
              },
            ],
          },
          {
            activation: false,
            version: "G CVT",
            fuel: "Petrol",
            years: [
              {
                activation: false,
                year: "2020",
                transmission: "Automatic",
                tier: 2,
                originalprice: 570000000,
              },
            ],
          },
        ],
      },
      {
        activation: true,
        model: "Camry",
        type: "Sedan",
        versions: [
          {
            activation: true,
            version: "2.0Q",
            fuel: "Petrol",
            years: [
              {
                activation: true,
                year: "2020",
                transmission: "Automatic",
                tier: 3,
                originalprice: 1160000000,
              },
              {
                activation: true,
                year: "2021",
                transmission: "Automatic",
                tier: 3,
                originalprice: 1230000000,
              },
            ],
          },
        ],
      },
      {
        activation: false,
        model: "Corolla Cross",
        type: "SUV",
        versions: [
          {
            activation: false,
            version: "1.8V",
            fuel: "Petrol",
            years: [
              {
                activation: false,
                year: "2022",
                transmission: "Automatic",
                tier: 3,
                originalprice: 860000000,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    brand: "Mercedes-Benz",
    activation: true,
    models: [
      {
        activation: true,
        model: "C-Class",
        type: "Sedan",
        versions: [
          {
            activation: true,
            version: "C200 Avantgarde",
            fuel: "Petrol",
            years: [
              {
                activation: true,
                year: "2021",
                transmission: "Automatic",
                tier: 4,
                originalprice: 1700000000,
              },
              {
                activation: true,
                year: "2022",
                transmission: "Automatic",
                tier: 4,
                originalprice: 1780000000,
              },
            ],
          },
        ],
      },
      {
        activation: true,
        model: "E-Class",
        type: "Sedan",
        versions: [
          {
            activation: true,
            version: "E300 AMG",
            fuel: "Petrol",
            years: [
              {
                activation: true,
                year: "2020",
                transmission: "Automatic",
                tier: 5,
                originalprice: 2920000000,
              },
              {
                activation: true,
                year: "2022",
                transmission: "Automatic",
                tier: 5,
                originalprice: 3209000000,
              },
            ],
          },
        ],
      },
      {
        activation: false,
        model: "A-Class",
        type: "Hatchback",
        versions: [
          {
            activation: false,
            version: "A200",
            fuel: "Petrol",
            years: [
              {
                activation: false,
                year: "2019",
                transmission: "Automatic",
                tier: 3,
                originalprice: 1450000000,
              },
            ],
          },
        ],
      },
    ],
  },
];

const sellerA = "65f1a1a1a1a1a1a1a1a1a1a1";
const sellerB = "65f1b2b2b2b2b2b2b2b2b2b2";
const sellerC = "65f1c3c3c3c3c3c3c3c3c3c3";
const bidderA = "65f1d4d4d4d4d4d4d4d4d4d4";
const bidderB = "65f1e5e5e5e5e5e5e5e5e5e5";
const buyerA = "65f1f6f6f6f6f6f6f6f6f6f6";

export const cardata = [
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 22000,
      condition: 5,
      platecolor: 1,
      platenumber: "30A-123.45",
      startingprice: 455000000,
      images: [],
      description: "Toyota Vios E CVT 2021, one-owner, city-driven.",
      posteddate: new Date("2026-01-04"),
      location: "Hanoi",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verified",
    bid: {
      followers: 21,
      currentprice: 455000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 38000,
      condition: 4,
      platecolor: 1,
      platenumber: "29B-456.78",
      startingprice: 468000000,
      images: [],
      description: "Toyota Vios E CVT 2022, maintenance history available.",
      posteddate: new Date("2026-01-07"),
      location: "Hanoi",
      seller: sellerB,
      buyer: null,
    },
    progress: "In auction",
    bid: {
      followers: 45,
      currentprice: 481000000,
      bidders: [
        { userid: bidderA, amount: 475000000, time: new Date("2026-02-20T09:20:00Z") },
        { userid: bidderB, amount: 481000000, time: new Date("2026-02-20T09:25:00Z") },
      ],
      auctioncounter: 1,
      auctionSessionEndTime: new Date("2026-03-01T10:00:00Z"),
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 86000,
      condition: 3,
      platecolor: 2,
      platenumber: "43A-8123",
      startingprice: 398000000,
      images: [],
      description: "Toyota Vios 2021 for ride-hailing, stable engine.",
      posteddate: new Date("2026-01-10"),
      location: "Da Nang",
      seller: sellerC,
      buyer: null,
    },
    progress: "Finished auction",
    bid: {
      followers: 16,
      currentprice: 412000000,
      bidders: [
        { userid: bidderA, amount: 405000000, time: new Date("2026-02-10T14:00:00Z") },
        { userid: bidderB, amount: 412000000, time: new Date("2026-02-10T14:03:00Z") },
      ],
      auctioncounter: 2,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2020",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 42000,
      condition: 5,
      platecolor: 1,
      platenumber: "51H-223.34",
      startingprice: 960000000,
      images: [],
      description: "Toyota Camry 2.0Q 2020, premium interior in excellent condition.",
      posteddate: new Date("2026-01-12"),
      location: "Ho Chi Minh City",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verifying bidders",
    bid: {
      followers: 39,
      currentprice: 1005000000,
      bidders: [
        { userid: bidderA, amount: 995000000, time: new Date("2026-02-14T11:00:00Z") },
        { userid: bidderB, amount: 1005000000, time: new Date("2026-02-14T11:06:00Z") },
      ],
      auctioncounter: 1,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 61000,
      condition: 4,
      platecolor: 1,
      platenumber: "30F-5588",
      startingprice: 1040000000,
      images: [],
      description: "Toyota Camry 2021, family-used, full service book.",
      posteddate: new Date("2026-01-15"),
      location: "Hanoi",
      seller: sellerB,
      buyer: null,
    },
    progress: "Setting up legal documents",
    bid: {
      followers: 33,
      currentprice: 1080000000,
      bidders: [
        { userid: bidderB, amount: 1080000000, time: new Date("2026-02-16T15:00:00Z") },
      ],
      auctioncounter: 3,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2020",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 98000,
      condition: 3,
      platecolor: 3,
      platenumber: "15A-993.21",
      startingprice: 885000000,
      images: [],
      description: "Toyota Camry 2020, long-distance use, good chassis.",
      posteddate: new Date("2026-01-18"),
      location: "Da Nang",
      seller: sellerC,
      buyer: null,
    },
    progress: "Pending verification",
    bid: {
      followers: 9,
      currentprice: 885000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "C-Class",
      type: "Sedan",
      version: "C200 Avantgarde",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 4,
    },
    car: {
      mileage: 18000,
      condition: 5,
      platecolor: 1,
      platenumber: "30K-678.90",
      startingprice: 1520000000,
      images: [],
      description: "Mercedes C200 2021, luxury sedan, low mileage.",
      posteddate: new Date("2026-01-20"),
      location: "Hanoi",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verified",
    bid: {
      followers: 66,
      currentprice: 1520000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "C-Class",
      type: "Sedan",
      version: "C200 Avantgarde",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 4,
    },
    car: {
      mileage: 34000,
      condition: 4,
      platecolor: 1,
      platenumber: "51G-441.12",
      startingprice: 1610000000,
      images: [],
      description: "Mercedes C200 2022, black edition, dealer-maintained.",
      posteddate: new Date("2026-01-22"),
      location: "Ho Chi Minh City",
      seller: sellerB,
      buyer: null,
    },
    progress: "In auction",
    bid: {
      followers: 72,
      currentprice: 1685000000,
      bidders: [
        { userid: bidderA, amount: 1650000000, time: new Date("2026-02-21T08:00:00Z") },
        { userid: bidderB, amount: 1685000000, time: new Date("2026-02-21T08:09:00Z") },
      ],
      auctioncounter: 2,
      auctionSessionEndTime: new Date("2026-03-02T08:30:00Z"),
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "E-Class",
      type: "Sedan",
      version: "E300 AMG",
      fuel: "Petrol",
      year: "2020",
      transmission: "Automatic",
      tier: 5,
    },
    car: {
      mileage: 29000,
      condition: 5,
      platecolor: 1,
      platenumber: "30M-500.55",
      startingprice: 2510000000,
      images: [],
      description: "Mercedes E300 AMG 2020, flagship comfort and power.",
      posteddate: new Date("2026-01-25"),
      location: "Hanoi",
      seller: sellerC,
      buyer: null,
    },
    progress: "Finished auction",
    bid: {
      followers: 58,
      currentprice: 2630000000,
      bidders: [
        { userid: bidderA, amount: 2590000000, time: new Date("2026-02-11T12:15:00Z") },
        { userid: bidderB, amount: 2630000000, time: new Date("2026-02-11T12:28:00Z") },
      ],
      auctioncounter: 1,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "E-Class",
      type: "Sedan",
      version: "E300 AMG",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 5,
    },
    car: {
      mileage: 12000,
      condition: 5,
      platecolor: 5,
      platenumber: "80A-987.65",
      startingprice: 2870000000,
      images: [],
      description: "Mercedes E300 AMG 2022 imported unit, pristine condition.",
      posteddate: new Date("2026-01-28"),
      location: "Ho Chi Minh City",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verifying bidders",
    bid: {
      followers: 81,
      currentprice: 2980000000,
      bidders: [
        { userid: bidderA, amount: 2950000000, time: new Date("2026-02-18T10:10:00Z") },
        { userid: bidderB, amount: 2980000000, time: new Date("2026-02-18T10:16:00Z") },
      ],
      auctioncounter: 1,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 74000,
      condition: 3,
      platecolor: 2,
      platenumber: "43C-7012",
      startingprice: 425000000,
      images: [],
      description: "Vios 2022, commercial usage, engine runs smoothly.",
      posteddate: new Date("2026-02-01"),
      location: "Da Nang",
      seller: sellerB,
      buyer: null,
    },
    progress: "Rejected",
    bid: {
      followers: 7,
      currentprice: 425000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 51000,
      condition: 4,
      platecolor: 4,
      platenumber: "29D-301.04",
      startingprice: 1015000000,
      images: [],
      description: "Camry 2021, paint refreshed, interior still premium.",
      posteddate: new Date("2026-02-03"),
      location: "Hanoi",
      seller: sellerC,
      buyer: null,
    },
    progress: "Cancel request",
    bid: {
      followers: 18,
      currentprice: 1015000000,
      bidders: [],
      auctioncounter: 1,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "C-Class",
      type: "Sedan",
      version: "C200 Avantgarde",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 4,
    },
    car: {
      mileage: 46000,
      condition: 4,
      platecolor: 1,
      platenumber: "30E-774.11",
      startingprice: 1460000000,
      images: [],
      description: "C200 2021, service at authorized workshop.",
      posteddate: new Date("2026-02-05"),
      location: "Hanoi",
      seller: sellerA,
      buyer: null,
    },
    progress: "Cancelled",
    bid: {
      followers: 24,
      currentprice: 1460000000,
      bidders: [],
      auctioncounter: 1,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "E-Class",
      type: "Sedan",
      version: "E300 AMG",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 5,
    },
    car: {
      mileage: 26000,
      condition: 5,
      platecolor: 1,
      platenumber: "51K-412.98",
      startingprice: 2940000000,
      images: [],
      description: "E300 AMG 2022 with complete insurance package.",
      posteddate: new Date("2026-02-07"),
      location: "Ho Chi Minh City",
      seller: sellerB,
      buyer: buyerA,
    },
    progress: "Sold",
    bid: {
      followers: 74,
      currentprice: 3040000000,
      bidders: [
        { userid: bidderA, amount: 3010000000, time: new Date("2026-02-12T13:10:00Z") },
        { userid: bidderB, amount: 3040000000, time: new Date("2026-02-12T13:18:00Z") },
      ],
      auctioncounter: 2,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 150000,
      condition: 2,
      platecolor: 6,
      platenumber: "29A-3001",
      startingprice: 315000000,
      images: [],
      description: "High-mileage Vios 2021, suitable for budget buyers.",
      posteddate: new Date("2026-02-09"),
      location: "Da Nang",
      seller: sellerC,
      buyer: null,
    },
    progress: "Pending verification",
    bid: {
      followers: 4,
      currentprice: 315000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2020",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 33000,
      condition: 5,
      platecolor: 1,
      platenumber: "92A-889.20",
      startingprice: 980000000,
      images: [],
      description: "Camry 2020 executive-owned, very clean cabin.",
      posteddate: new Date("2026-02-10"),
      location: "Da Nang",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verified",
    bid: {
      followers: 28,
      currentprice: 980000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "C-Class",
      type: "Sedan",
      version: "C200 Avantgarde",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 4,
    },
    car: {
      mileage: 27000,
      condition: 5,
      platecolor: 1,
      platenumber: "30P-567.89",
      startingprice: 1635000000,
      images: [],
      description: "C200 2022 with AMG styling package.",
      posteddate: new Date("2026-02-12"),
      location: "Hanoi",
      seller: sellerB,
      buyer: null,
    },
    progress: "In auction",
    bid: {
      followers: 49,
      currentprice: 1670000000,
      bidders: [
        { userid: bidderA, amount: 1655000000, time: new Date("2026-02-22T08:40:00Z") },
        { userid: bidderB, amount: 1670000000, time: new Date("2026-02-22T08:45:00Z") },
      ],
      auctioncounter: 1,
      auctionSessionEndTime: new Date("2026-03-03T09:00:00Z"),
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "E-Class",
      type: "Sedan",
      version: "E300 AMG",
      fuel: "Petrol",
      year: "2020",
      transmission: "Automatic",
      tier: 5,
    },
    car: {
      mileage: 68000,
      condition: 4,
      platecolor: 2,
      platenumber: "43A-6677",
      startingprice: 2360000000,
      images: [],
      description: "E300 2020, comfort package and adaptive suspension.",
      posteddate: new Date("2026-02-13"),
      location: "Da Nang",
      seller: sellerC,
      buyer: null,
    },
    progress: "Finished auction",
    bid: {
      followers: 32,
      currentprice: 2410000000,
      bidders: [
        { userid: bidderA, amount: 2395000000, time: new Date("2026-02-17T16:12:00Z") },
        { userid: bidderB, amount: 2410000000, time: new Date("2026-02-17T16:16:00Z") },
      ],
      auctioncounter: 3,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Vios",
      type: "Sedan",
      version: "E CVT",
      fuel: "Petrol",
      year: "2022",
      transmission: "Automatic",
      tier: 2,
    },
    car: {
      mileage: 54000,
      condition: 4,
      platecolor: 1,
      platenumber: "29X-112.22",
      startingprice: 439000000,
      images: [],
      description: "Vios 2022 with stable CVT and fuel efficiency.",
      posteddate: new Date("2026-02-14"),
      location: "Hanoi",
      seller: sellerA,
      buyer: null,
    },
    progress: "Verifying bidders",
    bid: {
      followers: 22,
      currentprice: 446000000,
      bidders: [
        { userid: bidderB, amount: 446000000, time: new Date("2026-02-23T10:00:00Z") },
      ],
      auctioncounter: 2,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Toyota",
      model: "Camry",
      type: "Sedan",
      version: "2.0Q",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 3,
    },
    car: {
      mileage: 72000,
      condition: 3,
      platecolor: 1,
      platenumber: "51A-770.88",
      startingprice: 920000000,
      images: [],
      description: "Camry 2021, mixed city-highway usage.",
      posteddate: new Date("2026-02-16"),
      location: "Ho Chi Minh City",
      seller: sellerB,
      buyer: null,
    },
    progress: "Setting up legal documents",
    bid: {
      followers: 19,
      currentprice: 954000000,
      bidders: [
        { userid: bidderA, amount: 954000000, time: new Date("2026-02-24T14:33:00Z") },
      ],
      auctioncounter: 2,
      auctionSessionEndTime: null,
    },
  },
  {
    model: {
      brand: "Mercedes-Benz",
      model: "C-Class",
      type: "Sedan",
      version: "C200 Avantgarde",
      fuel: "Petrol",
      year: "2021",
      transmission: "Automatic",
      tier: 4,
    },
    car: {
      mileage: 39000,
      condition: 4,
      platecolor: 3,
      platenumber: "30T-8800",
      startingprice: 1495000000,
      images: [],
      description: "C200 2021, balanced performance and comfort.",
      posteddate: new Date("2026-02-18"),
      location: "Hanoi",
      seller: sellerC,
      buyer: null,
    },
    progress: "Verified",
    bid: {
      followers: 37,
      currentprice: 1495000000,
      bidders: [],
      auctioncounter: 0,
      auctionSessionEndTime: null,
    },
  },
];
